@startuml asset_type_class

class AssetType {
    str: asset_name
    Column[]: columns
    str: asset_table_name
    int: asset_type_id
    datetime: created
    datetime: updated
    Union[AssetType, int]: super_type
    bool: is_slave
    int: owner_id
    bool: bookable
    int: booking_type_id
}

@enduml