@startuml asset_type_db

class AssetType {
    INTEGER: primary_key
    VARCHAR: asset_name
    VARCHAR: asset_columns
    VARCHAR: asset_table_name
    DATETIME: created
    DATETIME: updated
    INTEGER: super_type
    BOOLEAN: is_slave
    INTEGER: owner_id
    INTEGER: booking_type_id
}

@enduml