@startuml test

allow_mixing

class AssetType {
    asset_type_id
    asset_name
    asset_table_name
    Column[]: columns
}

class Column {
    name
    datatype
    required
}

class Asset {
    asset_id
    AssetType: asset_type
    data
}

class AssetTypeManager {
    DbConnection db_connection
    create_asset_type(AssetType: asset_type)
    delete_asset_type(AssetType: asset_type)
    update_asset_type(AssetType: asset_type)
    check_asset_type_exists(AssetType: asset_type)
    get_all()
}

class AssetPageManager {
    DbConnection db_connection
    create_page(AssetDetailPage: asset_detail_page)
    delete_page(AssetType: asset_type)
    update_page(AssetDetailPage: asset_detail_page)
    check_page_exists(AssetType: asset_type)
    get_page(AssetType: asset_type)
    get_editor(AssetType: asset_type)
}

class AssetPage {
    Asset: asset
    PageLayout: page_layout
}

class PageLayout {
    format
    plugins [] Plugin
}

class AssetDetailPageManager {
    AssetType: asset_type
    DbConnection: db_connection
    create_page(AssetDetailPage: asset_detail_page)
    delete_page(Asset: asset)
    update_page(AssetDetailPage: asset_detail_page)
    check_page_exists(Asset: asset)
    get_page(Asset: asset)
    get_editor(Asset: asset)
}

class AssetDetailPage {
    Asset: asset
    PageLayout: page_layout
}

class AssetManager  {
    DbConnection db_connection
    AssetTypeManager asset_type_manager
    create_asset(Asset: asset)
    delete_asset(Asset: asset)
    update_asset(Asset: asset)
    get_all(AssetType: asset_type)
}

interface DbConnection {
    get()
    commit()
    close()
    read()
    write_dict()
    create_table()
    delete_table()
    get_table_info()
    check_table_exists()
}

interface Plugin {

}

database database

DbConnection .> database
DbConnection --o AssetManager
DbConnection --o AssetTypeManager
DbConnection --o AssetPageManager
DbConnection --o AssetDetailPageManager

AssetTypeManager --o AssetManager
AssetTypeManager .. AssetType

AssetManager .. Asset

AssetType --o AssetPageManager

Column --o AssetType

AssetPageManager .. AssetPage

AssetDetailPageManager .. AssetDetailPage

PageLayout --o AssetDetailPage
PageLayout --o AssetPage

Plugin --o PageLayout

@enduml