@startuml test
class AssetType {
    asset_type_id
    asset_name
    asset_table_name
    Column[]: columns
}

class Column {
    name
    datatype
    required
}

class Asset {
    asset_id
    AssetType: asset_type
    data
}

class AssetTypeManager {
    DbConnection db_connection
    create_asset_type(AssetType: asset_type)
    delete_asset_type(AssetType: asset_type)
    update_asset_type(AssetType: asset_type)
    check_asset_type_exists(AssetType: asset_type)
    get_all()
}

class AssetPageManager {
    DbConnection db_connection
}

class AssetPage {

}

class AssetDetailPageManager {

}

class ResouceDetailPage {
    
}

class AssetManager  {
    DbConnection db_connection
    create_asset(Asset: asset)
    delete_asset(Asset: asset)
    update_asset(Asset: asset)
    get_all(AssetType: asset_type)
}

interface DbConnection {
    get()
    commit()
    close()
    read()
    write_dict()
    create_table()
    delete_table()
    get_table_info()
    check_table_exists()
}

interface Plugin {

}



@enduml